# Generated by Django 2.1.5 on 2019-03-28 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 16, 7, 30, 424026), editable=False),
        ),
    ]
